general:
  # The country you live in, this defaults to NL when not set.
  country: NL
  # The providers you want to check, for example when you own
  # Netflix and Amazon subscription (defaults to netflix):
  providers:
    - netflix
    - amazon prime video

tmdb:
  # The TMDB API Key, this is free, you will only need a account.
  # See: https://www.themoviedb.org/signup
  api_key: 'secret'

radarr:
  # The Radarr base url (include http of https)
  url: 'https://localhost:7878'
  # The Radarr api key
  api_key: 'secret'
  # Verify the SSL connection
  verify_ssl: false
